### ISSUE TITLE
ModuleNotFoundError: No module named 'Pycord'

### ISSUE THREAD

**Issue by nav-github01001** [Pycord-Development/Pycord.Wavelink#12]
There is an issue with the name pycord.wavelink as there is a '.' in the name, Python perceives 'pycord' as a module and 'wavelink' as a submodule 
![image](https://user-images.githubusercontent.com/78836383/147901938-4be9fd66-931c-4b4f-a910-f5a8e89680f9.png)
![image](https://user-images.githubusercontent.com/78836383/147901963-6f088fee-4be9-4df3-adce-61467704a15a.png)

**Comment by Makiyu-py** [comment]
It's supposed to be like that.

Before (@ `1.0.0b40`), it installs and works as fine.

The problem right now (the current release, `1.0.0b42`, and `1.0.0b41` I suspect) is that it's not installing the package. [I already reported this in the Discord](https://discord.com/channels/881207955029110855/881735314987708456/927432707653369878).

**Comment by SomeSniperBoi** [comment]
Same issue ;-;

**Comment by Dorukyum** [comment]
Why did you use capital case for Pycord? The module name is all lowercase.

**Comment by nav-github01001** [comment]
> Why did you use title case for Pycord? The module name is all lowercase.

bruh i tried lowercase but nope

**Comment by ju** [comment]
Having the same issue with `import pycord.wavelink as wavelink` on the latest version of the development branch of pycord and `pycord.wavelink==1.0.0b42` installed.

**Comment by Luc1412** [comment]
The whole pycord.wavelink directory is missing in the site-packages dir when you install this dependency. Just the list-info is present.
<img width="394" alt="Screenshot 2022-01-07 at 22 31 53" src="https://user-images.githubusercontent.com/24532065/148610184-8083e678-8663-4eb5-816c-28a12dc6d15a.png">

**Comment by Luc1412** [comment]
The whole pycord.wavelink directory is missing in the site-packages dir when you install this dependency. Just the list-info is present.
<img width="394" alt="Screenshot 2022-01-07 at 22 31 53" src="https://user-images.githubusercontent.com/24532065/148610184-8083e678-8663-4eb5-816c-28a12dc6d15a.png">

**Comment by nav-github01001** [comment]
> The whole pycord.wavelink directory is missing in the site-packages dir when you install this dependency. Just the dist-info is present.

Then something wrong in setup.py configuration

**Comment by Makiyu-py** [comment]
Fixed on 25e9ab9d02e32c2b570fbe56be2eb9d4be130602 :3

Try re-installing now!
