### ISSUE TITLE
Make wavelink a pycord extension

### ISSUE THREAD

**Issue by Luc1412** [Pycord-Development/Pycord.Wavelink#15]
I think a smart implementation of this library would be as an extension by moving it into the discord/ext/wavelink namespace.

Also the library name currently is a bit unconventional. pycord-ext-wavelink or py-cord-ext-wavelink would be better by following the naming conventions from Danny (menu extension)

**Comment by Luc1412** [comment]
> As Pycord.Wavelink is under another license it would have to be remade to work with our current license.

Are you sure it needs another license? I don't intend to merge it into the pycord repo. Just the directory and pipy name should be changed accordingly to my issue.

**Comment by VincentRPS** [comment]
> > As Pycord.Wavelink is under another license it would have to be remade to work with our current license.
> 
> Are you sure it needs another license? I don't intend to merge it into the pycord repo. Just the directory and pipy name should be changed accordingly to my issue.

wdym?

**Comment by Luc1412** [comment]
> wdym?

Here a good example from Danny: https://github.com/Rapptz/discord-ext-menus 
Extensions doesn't need to be placed in the same repo as the extendable project itself.
