### ISSUE TITLE
Missing some Wavelink objects

### ISSUE THREAD

**Issue by KosmicAnomaly** [Pycord-Development/Pycord.Wavelink#28]
`wavelink.Client`, `wavelink.eqs.Equalizer`, `wavelink.meta.WavelinkMixin`, and `wavelink.events` (such as `wavelink.events.TrackEnd`) were not brought over into the pycord version of wavelink

**Comment by Makiyu-py** [comment]
This is a fork of the now-unmaintained [1.0 branch in the original wavelink repo](https://github.com/PythonistaGuild/Wavelink/tree/1.0), which intentionally removed these features/objects.
