### ISSUE TITLE
Pycord.Wavelink is not Compatible with Pycord

### ISSUE THREAD

**Issue by Pysics** [Pycord-Development/Pycord.Wavelink#39]
I am not able to use **Pycord.Wavelink** with **Pycord**. Can this be fixed as soon as possible?

**Comment by Om1609** [comment]
Wdym "Pycord.Wavelink is not Compatible with Pycord" ?

Please provide more details

**Comment by Pysics** [comment]
I am not able to use it with the Pycord library.

**Comment by Om1609** [comment]
What version of Pycord and Pycord.Wavelink are you using? 
Telling that you are not able to use it doesn't give any info. 

Any errors? Or what
