### ISSUE TITLE
Hey, is this fork being maintained?

### ISSUE THREAD

**Issue by egeakman** [Pycord-Development/Pycord.Wavelink#9]
Since the last commit was on November 1st, I was wondering if this fork is maintained? Thanks in advance.

**Comment by Lulalaby** [comment]
At the actual state it only has a few rewrites to work with pycord.

I think the best answer rn is semi-maintained.

We're busy with working for the release of pycord v2 atm

**Comment by egeakman** [comment]
Thank you for the answer. Good luck with pycord v2 🚀
